/**:
    ros__parameters:
        lio:
            operation_mode: "offline_map"
            realtime:
                max_lidar_queue: 100000
                max_imu_queue: 1000000
            async_map:
                queue_depth: 1
                drop_policy: "drop_oldest"
            offline:
                bag_path: ""
                output_pcd_path: "PCD/offline_map.pcd"
                save_on_finish: True

        use_imu_as_input: False
        prop_at_freq_of_imu: True
        check_satu: True
        init_map_size: 100
        point_filter_num: 1
        space_down_sample: True
        filter_size_surf: 0.05
        filter_size_map_internal: 0.15
        filter_size_map_publish: 0.1
        filter_size_map_save: 0.1
        ivox_nearby_type: 18
        runtime_pos_log_enable: False

        common:
            lid_topic: "livox/lidar"
            imu_topic: "livox/imu"
            con_frame: False
            con_frame_num: 1
            cut_frame: False
            cut_frame_time_interval: 0.1
            time_diff_lidar_to_imu: 0.0

        preprocess:
            lidar_type: 1
            scan_line: 4
            timestamp_unit: 3
            blind: 0.5

        mapping:
            imu_en: True
            extrinsic_est_en: False
            imu_time_inte: 0.005
            lidar_time_inte: 0.1
            satu_acc: 3.0
            satu_gyro: 35.0
            acc_norm: 1.0
            lidar_meas_cov: 0.01
            acc_cov_output: 500.0
            gyr_cov_output: 1000.0
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            imu_meas_acc_cov: 0.01
            imu_meas_omg_cov: 0.01
            gyr_cov_input: 0.01
            acc_cov_input: 0.1
            plane_thr: 0.1
            match_s: 81.0
            ivox_grid_resolution: 2.0
            gravity: [0.0, 0.0, -9.810]
            gravity_init: [0.0, 0.0, -9.810]
            extrinsic_T: [-0.011, -0.02329, 0.04412]
            extrinsic_R: [1.0, 0.0, 0.0,
                          0.0, 1.0, 0.0,
                          0.0, 0.0, 1.0]

        odometry:
            publish_odometry_without_downsample: False
            enable_2d_mode: False

        publish:
            path_en: False
            scan_publish_en: False
            scan_bodyframe_pub_en: False
            map_publish_en: False
            map_publish_interval: 20
            tf_send_en: False
            odom_topic: "odom"
            cloud_registered_topic: "cloud_registered"
            cloud_registered_body_topic: "cloud_registered_body"
            map_topic: "map_cloud"
            path_topic: "path"

        frame:
            odom_frame_id: "odom"
            base_frame_id: "base_link"
            cloud_registered_frame_id: "odom"
            cloud_registered_body_frame_id: "base_link"
            map_frame_id: "odom"

        pcd_save:
            pcd_save_en: False
            save_on_shutdown: False
            save_period_sec: 0.0
            save_path: "PCD/offline_map.pcd"
